#!/usr/bin/env python

import argparse
import pathlib
import sys
from os.path import exists

import docxreviews2txt

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract review changes and comments from a docx file as plain text.")
    parser.add_argument("docx", help="input docx", type=pathlib.Path)
    parser.add_argument('--save_txt', help='save review as txt', action="store_true")
    parser.add_argument('--save_p_xml', help='save extracted paragraphs xml for debugging', action="store_true")
    parser.add_argument('--version', help='show version', action='version',
                        version='%(prog)s ' + docxreviews2txt.__version__)
    argv = sys.argv[1:]
    args = parser.parse_args(argv)
    verbose = not args.save_p_xml and not args.save_txt
    docx_reviews = docxreviews2txt.DocxReviews(args.docx, verbose)
    docx_reviews.parse()
    if args.save_p_xml:
        docx_reviews.save_xml_p_elems()
    if args.save_txt:
        docx_reviews.save_reviews_to_file()
    exit()
